spring.mvc.view.suffix=.html

# Conexión / Docker usando las variables de entorno
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${JDBC_USER}
spring.datasource.password=${JDBC_PASSWORD}
spring.datasource.driver-class-name=${JDBC_DRIVER}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Parámetros del Pool de Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration