version: '3.8'

services:
  postgresdb:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: donPeppeDB
      POSTGRES_USER: donPeppe
      POSTGRES_PASSWORD: qwerty12345
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: